[tox]
envlist = unit, int, format, lint
skipsdist = true

[testenv]
allowlist_externals = poetry
commands_pre = poetry install --with dev

[testenv:unit]
commands = poetry run pytest tests/unit {posargs}

[testenv:int]
commands = poetry run pytest tests/integration {posargs}

[testenv:format]
commands =
    poetry run ruff check --select F401 --fix {posargs:.}
    poetry run isort {posargs:.}
    poetry run black {posargs:.}
    poetry run ruff format {posargs:.}

[testenv:lint]
commands = poetry run ruff check {posargs:.}
